# Generated by Django 3.0.8 on 2020-07-07 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 23, 55, 58, 531488), editable=False),
        ),
    ]
