# Generated by Django 3.0.8 on 2020-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0005_auto_20200707_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='Delhi', max_length=100),
        ),
    ]
